spring:
  application:
    name: Pharos-Register-Service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:5555/pharos.register
    username: root
    password: Q1.w2-e3.r4
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 1111


